<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MohamedSci" failures="2" tests="3" name="runner.TestRunner" time="46.521" errors="0" timestamp="2023-10-29T20:01:41 EET" skipped="0">
  <testcase classname="runner.TestRunner" name="assertCurrebtURL" time="20.973"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.884">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at steps.E2ETests.he_search_for(E2ETests.java:39)
at ✽.Customer inputs "ترابيزة" in the SearchBox and Submit(file:///C:/Users/moham/OneDrive/Desktop/AAIB_Technical_challenge_updated/AAIB_Technical_challenge/1.Amazon/src/test/java/features/End2End_Tests.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="21.664">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at steps.E2ETests.he_search_for(E2ETests.java:39)
at ✽.Customer inputs "قلم" in the SearchBox and Submit(file:///C:/Users/moham/OneDrive/Desktop/AAIB_Technical_challenge_updated/AAIB_Technical_challenge/1.Amazon/src/test/java/features/End2End_Tests.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.TestRunner -->
